### ISSUE TITLE
Selecting fields

### ISSUE THREAD

**Issue by ChuPhong** [joelwmale/cogent-js#12]
In package laravel-query-builder:
```
GET /users?fields[users]=id,name
```

But cogent-js:
```
GET /users?fields=id,name
```

Please fix

**Comment by joelwmale** [comment]
The next version (v1.0.6) will fix this. Sorry for the late response + fix.

**Comment by joelwmale** [comment]
v2.0.0 has been released @ChuPhong which fixes this. It's a major release because I renamed 2 functions: `append()` -> `appends()` and `include()` -> `includes()`.
