### ISSUE TITLE
Module not found: Can't resolve './Query'

### ISSUE THREAD

**Issue by Armalon** [joelwmale/cogent-js#29]
Failed to compile.
Module not found: Can't resolve './Query' in './node_modules/cogent-js/build'

**Comment by Armalon** [comment]
Thank you for this fix though: "Update fields filter to include model"!

**Comment by Armalon** [comment]
The error above can be seen when this module is used as a part or the React app. If you run it separately like in the README.md file then you can see the following:

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /home/armalon/projects/innoscripta/test/node_modules/cogent-js/build/index.js
- /home/armalon/projects/innoscripta/test/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/armalon/projects/innoscripta/test/node_modules/cogent-js/build/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/armalon/projects/innoscripta/test/node_modules/cogent-js/build/index.js',
    '/home/armalon/projects/innoscripta/test/index.js'
  ]
}

**Comment by brentjett** [comment]
Same issue. Any movement on this?

**Comment by tommy70404** [comment]
Same problem here, any update?

**Comment by acabreragnz** [comment]
Same problem here, by the meantime I copied your files directly in my project.

**Comment by joelwmale** [comment]
I'll take a look at this today sorry guys. Will investigate and see what is going on.

**Comment by jimtaylor123** [comment]
This appears to be because when the command 'babel src -d build' is run when installing the package, it fails to copy over Query.js and Parser.js into the build folder. I don't know enough about why this is happening to submit a PR.

**Comment by boxxroom** [comment]
Thanks for the great package @joelwmale. I also appear to be having the same issue with an unresolvable `'./Query'`

```js
ERROR in ./node_modules/cogent-js/build/index.js 15:36-54
```

**Comment by joelwmale** [comment]
Can anyone create a PR to fix this issue?

**Comment by steveerg** [comment]
Same issue, any update?

**Comment by teetlaja** [comment]
Are there any updates with this?

**Comment by Dibbyo456** [comment]
Any patch?

**Comment by ankur99** [comment]
yo any updates?

**Comment by harryqt** [comment]
Use this as replacement, works fine. https://github.com/coderello/js-query-builder

**Comment by joelwmale** [comment]
Thanks @Dibbyo456. Sorry guys, I just don't have time to maintain this anymore.
